#!/usr/bin/env perl
use strict;
use warnings;

$| ++;

return sub
{
    my $x = 75;
    my ( @df, @x ) = `df -ih`;
    my $title = shift @df;

    map{ push @x, $_ if  $_ =~ m#^/dev/# && $_ =~ /(\d+)%/ && $1 && $1 >= $x; }@df;

    map{ print $_ }( $title, @x ) if @x;

    return scalar @x;
}
