#!/bin/sh
ulimit -n 655350;ulimit -u 102400;ulimit -s 10240;
exec $MYDanPATH/dan/tools/fileupdate  --output $MYDanPATH/etc/agent/whitelist --url https://raw.githubusercontent.com/MYDan/openapi/master/config/whitelist 2>&1
