#!/usr/bin/env perl
use strict;
use warnings;

use Data::Dumper;
use MYDan::Util::OptConf;

$| ++;

my $option = MYDan::Util::OptConf->load();

if( my $name = shift )
{
    my ( $n, $k ) = split /\./, $name, 2;
    my %o = $option->get()->dump( $n );
    if( $k )
    {
        print "$o{$k}\n";
    }
    else
    {
        print Dumper \%o;   
    }

}
else { print Dumper $option; }
