#!/usr/bin/env perl
use strict;
use warnings;

use MYDan::Util::FastMD5;
use MYDan::Util::OptConf;

$MYDan::Util::OptConf::ARGC = 1;

=head1 SYNOPSIS

 $0 /path/file 
   
=cut

my $option = MYDan::Util::OptConf->load();
$option->assert() unless my $file = shift @ARGV;

print MYDan::Util::FastMD5->hexdigest( $file ), "  $file\n";
