#!/usr/bin/env perl

use strict;
use warnings;

use YAML::XS;
use File::Spec;

use MYDan::Util::OptConf;
use MYDan::Util::Gateway;

$| ++;

$MYDan::Util::OptConf::THIS = 'util';

=head1 SYNOPSIS

 $0 
 $0 on | off
 $0 on abc 
 $0 off foo bar
 $0 --help 

=cut

my $option = MYDan::Util::OptConf->load();
my %o = $option->get()->dump();

my $gateway = MYDan::Util::Gateway->new( "$o{conf}/gateway" );

unless( @ARGV ) { $gateway->status(); exit; }

my $ctrl = shift @ARGV;

$option->assert() unless $ctrl eq 'on' || $ctrl eq 'off';

$ctrl eq 'on' ? $gateway->on( @ARGV ) : $gateway->off( @ARGV );
