#!/usr/bin/env perl

use strict;
use warnings;

use YAML::XS;
use File::Spec;

use MYDan::Util::ExpSSH;
use MYDan::Util::OptConf;

$| ++;

$MYDan::Util::OptConf::ARGC = -1;
$MYDan::Util::OptConf::THIS = 'util';

=head1 SYNOPSIS

 $0 host [user]
 $0 --user dan host [user]

=cut

my $option = MYDan::Util::OptConf->load();
my %o = $option->get( qw( user=s ) )->dump();

die "cannot resolve host\n" unless MYDan::Util::ExpSSH->new()
    ->conn( pass => "$o{conf}/pass", user => $o{user}, host => shift, sudo => shift );
