#!/usr/bin/env perl

use strict;
use warnings;

use YAML::XS;
use File::Spec;

use MYDan::Util::ExpSSH;
use MYDan::Util::OptConf;

$| ++;

$MYDan::Util::OptConf::ARGC = -1;

=head1 SYNOPSIS

 $0 host [user]

=cut

my %o = MYDan::Util::OptConf->load()->get()->dump();
my $user = `logname`; chomp $user;
my $pass = $ENV{PASSWD};


unless( $pass )
{
    my $conf = File::Spec->join( ( getpwnam $user )[7], '.go' );
    $conf = eval { YAML::XS::LoadFile $conf };
    $pass = $conf->{$user} if $conf && ref $conf eq 'HASH' && defined $conf->{$user};
}

die "cannot resolve host\n" unless MYDan::Util::ExpSSH->new()
    ->conn( pass => $pass, user => $user, host => shift, sudo => shift );
