#!/usr/bin/env perl
use warnings;  
use strict;  
  
use MYDan::Agent::Load;
use Fcntl qw(:flock SEEK_END);
 
$| ++;

=head1 SYNOPSIS

 $0 -range host [--sp srcfile] [--verbose]

     [--dp dstfile (default sp )]

     [--sudo sudoer ]
     [--user username (default `logname`)]
     [--timeout seconds (default 500)]

=cut

$MYDan::Util::OptConf::THIS = 'agent';
my $option = MYDan::Util::OptConf->load();
my %o = $option->get( 
    qw( range=s sp=s dp=s verbose user=s sudo=s timeout=i ) 
)->dump();

$option->assert( 'range', 'sp' );
$o{dp} ||= $o{sp};

$o{user} = `logname` and chop $o{user} unless $o{user};

MYDan::Agent::Load->new(
    node => $o{range}, 
    map{ $_ => $o{$_} }qw( sp dp )
)->run( %o );
