#!/usr/bin/env perl

use strict;
use warnings;

use MYDan::Node;
use MYDan::Util::MIO::CMD;
use MYDan::Util::OptConf;

$| ++;

$MYDan::Util::OptConf::ARGC = -1;
@MYDan::Util::OptConf::CONF = qw( pass_through );

=head1 SYNOPSIS

 $0 -r range [--timeout seconds] [--max number] [--noop] cmd ..

=cut
my $option = MYDan::Util::OptConf->load();
my %o = $option->get( qw( range=s timeout=i max=i noop ) )->dump();

$option->assert( 'range' );

my $range = MYDan::Node->new( $option->dump( 'range' ) );
my %cmd = map { $_ => \@ARGV } $range->load( delete $o{range} )->list();

my %result = MYDan::Util::MIO::CMD->new( %cmd )->run( %o );
my %mesg;

while ( my ( $io, $mesg ) = each %result )
{
    while ( my ( $mesg, $node ) = each %$mesg )
    {
        push @{ $mesg{$io} }, join ': ', $range->load( $node )->dump, $mesg;
    }
}

for my $io ( sort keys %mesg )
{
    print "---\n$io:\n";
    map { print "  $_" } @{ $mesg{$io} };
}

exit 0;
