#!/usr/bin/env perl

use strict;
use warnings;
use File::Spec;

use MYDan::Node;
use MYDan::Util::OptConf;
use MYDan::Agent::Client;

$| ++;

$MYDan::Util::OptConf::THIS = 'agent';
$MYDan::Util::OptConf::ARGC = -1;
@MYDan::Util::OptConf::CONF = qw( no_ignore_case pass_through ); 

=head1 SYNOPSIS

 $0 -r range [--user username] [--timeout seconds] [--max number] [--proxy] cmd ..

[--proxy-name foo] [--proxy-timeout 86400] [--proxy-max 32] [--env "A=123;B=abc" ]

=cut
my $option = MYDan::Util::OptConf->load();
my %o = $option->get(
     qw( range=s user=s timeout=i max=i port=i proxy verbose 
     proxy-name=s proxy-timeout=i proxy-max=i )
)->dump();

$option->assert( 'range' );

my $code = shift;
my $port = delete $o{port};
my %query = ( code => $code, logname => operator(), argv => argv( $code ) );

if( $o{env} )
{
    my %env;
    map{ my @env = split /=/, $_; $env{$env[0]} = $env[1] if 2 == @env }split /;/, $o{env};
    $query{env} = \%env if %env;
}

$query{user} = delete $o{user} if $o{user};

my $range = MYDan::Node->new( $option->dump( 'range' ) );


my $client = MYDan::Agent::Client->new( 
    map { join ':', $_, $port } $range->load( delete $o{range} )->list
);

my %result = $client->run( %o, query => \%query ); 

YAML::XS::DumpFile \*STDERR, \%result if %result;
exit 0;

sub operator
{
    my $name = `logname`; chop $name; return $name;
}

sub argv
{
    my $code = File::Spec->join( $o{argv}, shift );
    return -f $code && ( $code = do $code ) && ref $code eq 'CODE'
        ? &$code( @ARGV ) : \@ARGV;
}
