#!/usr/bin/env perl
use strict;
use warnings;
use MYDan::Node;
use MYDan::Util::OptConf;

use MYDan::VSSH;
use MYDan::VSSH::Execute;

$MYDan::VSSH::Execute::dan=1;

=head1 SYNOPSIS

 $0 [--range host] [--logname foo] [--user root]
    
=cut

my $option = MYDan::Util::OptConf->load();
my %o = $option->get( qw( range=s logname=s user=s) )->dump( 'vssh' );
my $range = MYDan::Node->new( $option->dump( 'range' ) );
 
$option->assert( 'range' );

exit unless my @node = $range->load( delete $o{range} )->list;

MYDan::VSSH->new( node => \@node, logname => operator(), %o )->run();

exit 0;

sub operator
{
    my $name = `logname`; chop $name; return $name;
}
