#!/home/s/ops/perl/bin/perl
use strict;
use warnings;

use FindBin qw( $RealBin );

use MYDan::Util::OptConf;
use MYDan::Util::Sudo;
use Data::Dumper;

MYDan::Util::Sudo->sudo();

$| ++;

our %deploy;
BEGIN { 
    %deploy = MYDan::Util::OptConf->load()->get()->dump( 'deploy' );
};

use lib $deploy{lib};
use DumpCrontab;

$MYDan::Util::OptConf::THIS = 'util';
my %util = MYDan::Util::OptConf->load()->set(  interval => 90 )->get( qw(  interval=i ) )->dump();
print Dumper \%util;


my $dump = DumpCrontab->new( 
    conn => "$util{conf}/conn",
    cron => "/etc/cron.d",
    name => 'cron.mould',
);

do
{
    print "check...\n";
    $dump->run();
}while( sleep $util{interval} );

