#!/usr/bin/env perl
use strict;
use warnings;
use YAML::XS;
use MYDan::API::AntDen;

local $/ = undef;

my ( %param, @r )= %{ YAML::XS::Load( <> ) };

my $argv = $param{argv};
my $api = MYDan::API::AntDen->new( addr => "http://127.0.0.1:3000" );
my $idie = sub{ print shift; exit 1; };

@r = eval{ $api->submitjob( %{$argv->{conf}} ); } if $argv->{ctrl} eq 'submitjob';
@r = eval{ $api->listjob( %{$argv->{conf}} ); } if $argv->{ctrl} eq 'listjob';
@r = eval{ $api->info( $argv->{conf}{jobid} ); } if  $argv->{ctrl} eq 'info';
@r = eval{ $api->stop( $argv->{conf}{jobid} ); } if $argv->{ctrl} eq 'stop';
@r = eval{ $api->taskinfo( $argv->{conf}{taskid} ); } if $argv->{ctrl} eq 'taskinfo';
@r = eval{ $api->resources(); } if $argv->{ctrl} eq 'resources';

&$idie( "err: $@" ) if $@;
print YAML::XS::Dump @r;

exit;
