#!/usr/bin/env perl
use strict;
use warnings;
use YAML::XS;
use MYDan::API::AntDen;

local $/ = undef;

my ( %param, @r )= %{ YAML::XS::Load( <> ) };

my $argv = $param{argv};
my $api = MYDan::API::AntDen->new( addr => "http://127.0.0.1:3000" );
my $idie = sub{ print shift; exit 1; };

my %version = ( cli => '1.0.01' , image => '1.0.01' );
for my $k ( keys %version )
{
    next unless $argv->{version} && $argv->{version}{$k};
    my $v = $argv->{version}{$k};

    $v =~ s/\D/./g;
    next if $v ge $version{$k};

    print "\n", '=' x 75, "\n";
    print "Your current $k version is $v. Need an update to $version{$k}\n";
    print "Get more help: https://antden.github.io\n";
    print '=' x 75, "\n";
    exit;
}

@r = eval{ $api->submitjob( %{$argv->{conf}}, owner => $param{user} ); } if $argv->{ctrl} eq 'submitjob';
@r = eval{ $api->listjob( $param{user} ); } if $argv->{ctrl} eq 'listjob';
@r = eval{ $api->info( $argv->{conf}{jobid}, $param{user} ); } if  $argv->{ctrl} eq 'info';
@r = eval{ $api->stop( $argv->{conf}{jobid}, $param{user} ); } if $argv->{ctrl} eq 'stop';
@r = eval{ $api->taskinfo( $argv->{conf}{taskid} ); } if $argv->{ctrl} eq 'taskinfo';
@r = eval{ $api->resources( $param{user} ); } if $argv->{ctrl} eq 'resources';
@r = eval{ $api->datasets( $param{user} ); } if $argv->{ctrl} eq 'datasets';

&$idie( "err: $@" ) if $@;
print YAML::XS::Dump @r;

exit;
