#!/usr/bin/env perl
use strict;
use warnings;
use YAML::XS;
use Digest::MD5;

eval
{
    local $/ = undef;
    my (  %param, $i ) = %{ YAML::XS::Load( <> ) };

    my ( $file, $position ) = @{$param{argv}} or "file undef";

    die "Can't open '$file': $!" unless open my  $fh, '+<', $file;

    printf "%d:%s:", (stat $file)[7], Digest::MD5->new()->addfile( $fh )->hexdigest();

    seek $fh, $position || 0, 0;
    while( <$fh> ) { print $_; }

    exit 0;
};
print $@;
exit 1;
