#!/usr/bin/env perl
use strict;
use warnings;
use YAML::XS;
use MYDan::Agent::Mrsync;

local $/ = undef;

my %param = %{ YAML::XS::Load( <> ) };

my %o = %{$param{argv}};

my $mrsync = MYDan::Agent::Mrsync->new
(
     map { $_ => delete $o{$_} } qw( sp dp src dst queryxdata ) 
);

my @failed = $mrsync->run( %o )->failed();

YAML::XS::DumpFile \*STDOUT, \@failed;

exit 0;
