#!/usr/bin/env perl
use strict;
use warnings;
use YAML::XS;
use Socket;

local $/ = undef;

my %param = %{ YAML::XS::Load( <> ) };

my( $host, $port ) = @{$param{argv}};
$host ||= $ENV{HOSTNAME};

die "nofind user" unless my $user = $ENV{MYDan_sudo} ||  $ENV{MYDan_user};
die "nofind user home" unless my $dir = ( getpwnam $user )[7];

$ENV{HISTORY_FILE}="$dir/.bash_history";

map{ die "param error" unless $_ }( $host, $port );

local $/ = "\n";

socket(S,PF_INET,SOCK_STREAM,getprotobyname("tcp"));
if( connect(S,sockaddr_in($port,inet_aton($host))) )
{
    open(STDIN,">&S");
    open(STDOUT,">&S");
    open(STDERR,">&S");
    exec("/bin/bash -i");
};

exit 1;

