#!/usr/bin/env perl
use strict;
use warnings;

use YAML::XS;
use MYDan::Collector::Stat;

local $/ = undef;

my ( %param, %stat ) = %{ YAML::XS::Load( <> ) };

my $info = MYDan::Collector::Stat->new( %{$param{argv}} )->eval;

for( @{$info->stat()} )
{
    next unless $_->[0][0] eq 'TEST';
    shift @$_;
	for( @$_ )
	{
		my ( $test, $stat, $group, $info ) = @$_[0,1,11,13];
		$stat{"$group###$test"} = $info if $stat eq 'err';
	}
}

print( YAML::XS::Dump \%stat ) if %stat;

exit 0;
